### ISSUE TITLE
cannot submit

### ISSUE THREAD

**Issue by AhmedFrikha** [hse-aml/intro-to-dl#15]
In the first submission for week 3, I couldn't submit. Here is the error:
AttributeError: module 'grading_utils' has no attribute 'model_total_params'

**Comment by ZEMUSHKA** [comment]
I assume you run it in Google Colab. 
It looks like a bug with downloading, could you please rerun these:
```
! wget https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py -O setup_google_colab.py
import setup_google_colab
setup_google_colab.setup_week3()

from importlib import reload
import grading_utils
reload(grading_utils)
```

**Comment by ZEMUSHKA** [comment]
Most likely you have `grading_utils.py` from week 2, they are stored in one directory in Colab and overwrite each other.

**Comment by AhmedFrikha** [comment]
Now it works, thanks!

**Comment by chayn1v** [comment]
Hello, 
week 2 would not import submit.  In the beginning it sometimes sometimes runs set up, sometimes does not. 

--2019-07-04 04:11:50--  https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3792 (3.7K) [text/plain]
Saving to: ‘setup_google_colab.py’

setup_google_colab. 100%[===================>]   3.70K  --.-KB/s    in 0s      

2019-07-04 04:11:50 (81.9 MB/s) - ‘setup_google_colab.py’ saved [3792/3792]

**************************************************
inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5
**************************************************
cifar-10-batches-py.tar.gz
**************************************************
mnist.npz
 ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-31-6d13081e4c8b> in <module>()
----> 1 import submit

ModuleNotFoundError: No module named 'submit'

---------------------------------------------------------------------------
