### ISSUE TITLE
explanation of "download_utils.py"

### ISSUE THREAD

**Issue by rezwanh001** [hse-aml/intro-to-dl#6]
```python
def link_all_keras_resources():
    link_all_files_from_dir("../readonly/keras/datasets/", os.path.expanduser("~/.keras/datasets"))
    link_all_files_from_dir("../readonly/keras/models/", os.path.expanduser("~/.keras/models"))
```
which datas are belong to the `datasets` and `models` dir ? (with name).

```python
def link_week_6_resources():
    link_all_files_from_dir("../readonly/week6/", ".")
```

which datas are belong to the `week6` dir ? (with name).

Please, explain this two function. I want to run `week-6` `image_captionong_project` into my local jupyter-notebook.

Please help me . THANKS

**Comment by ZEMUSHKA** [comment]
@rezwanulhaquerezwan, hi!

All the necessary files can be downloaded with https://github.com/hse-aml/intro-to-dl/blob/master/download_resources.ipynb in your local environment.

**Comment by rezwanh001** [comment]
Well. Thanks.

Where I will use `captions_train-val2014.zip`, `train2014.zip` and `val2014.zip` ?
Please Sir.

**Comment by ZEMUSHKA** [comment]
- captions_train-val2014.zip contains json with texts for images
- train2014_sample.zip is a sample of images we've prepared for you (will be used for visualization of results)
- val2014_sample.zip is another sample of images we've prepared for you (will be used for visualization of results)
